### ISSUE TITLE
Interpolation in raster

### ISSUE THREAD

**Issue by manbcn** [borysiasty/pointsamplingtool#11]
Hi!
How do you assign a value from the cell to the point? Do you use an interpolation method?
Thanks

**Comment by borysiasty** [comment]
By calling QgsRasterDataProvider.identify() [1]. If the raster has pyramids, the highest resolution is used, so no interpolation should occur. Do you get unexpected values?

[1] https://qgis.org/api/2.18/classQgsRasterDataProvider.html#ac70a015832189e617eba86d395f4273e

**Comment by manbcn** [comment]
We do not have pyramid. Only a grd file with cell size of 1m.
Thanks
