### ISSUE TITLE
Name length can exceed 10 chars

### ISSUE THREAD

**Issue by romainbh** [borysiasty/pointsamplingtool#13]
With the support of GeoPackage, the limitation of 10 chars in the name of the attributes is outdated.

**Comment by borysiasty** [comment]
Yes, I've mostly implemented it some months ago, but I hadn't enough time to finish and commit it. Hopefully I'll manage to make it done at some point in 2019.

**Comment by romainbh** [comment]
Wonderful, thanks a lot! This plugin is amazing ;-)

**Comment by samuel-rosa** [comment]
I wonder when you will have the time to update this. It would be a most welcome improvement.

**Comment by borysiasty** [comment]
Unfortunately I don't have any idea, as I'll have no free resources in predictable future :( In case someone was interested in implementing it, I just pushed my initial changes from 2018 into this branch: https://github.com/borysiasty/pointsamplingtool/tree/no10charslimit

But honestly speaking, instead of reviving this old plugin, I'd rather implement a new Processing algorithm called e.g. "Sample polygon values" (or even better "Sample vector values" with some tolerance for lines (and points). See also #16.

**Comment by MarianaOliveira94** [comment]
Thanks for this update!! but I'm running QGis on a windows and when I tried to install the plugin with this changes I got an error: **Couldn't load plugin 'pointsamplingtool-no10charslimit' due to an error when calling its classFactory() method** how can I solve it?

**Comment by borysiasty** [comment]
Sorry if I was unclear - it's unfinished and not supposed to be working. It's just my my initial work from a year ago I found and uploaded in case someone wants to continue it.

But as I said, I'd rather write a native Processing algorithms for vectors and meshes, based on the existing raster sampling: https://github.com/qgis/QGIS/blob/master/python/plugins/processing/algs/qgis/RasterSampling.py

**Comment by apazga** [comment]
I needed this feature to work in a case with hundreds of rasters, so I forked it and I directly removed the 10 char limitation.
Tested with current latest QGIS version (3.28) and it's working ok.

I'll leave the link to the fork here in case it helps someone (you can install the plugin downloading it as a ZIP file)
https://github.com/apazga/pointsamplingtool

EDIT: Tested with SHP and it's working too. If the user uses SHP as output and he doesn't change the names to fit the 10 char limit, then the attribute is truncated, but it's working anyway.

**Comment by borysiasty** [comment]
Thanks to @apazga it's finally solved!
