### ISSUE TITLE
Create points along line first

### ISSUE THREAD

**Issue by wolfefranklin** [borysiasty/pointsamplingtool#15]
Hi, first thank you for this awesome tool. I am current using it for my research and it has made my life a lot easier.

I am wondering whether a functionality can be added that will create points along vector lines first before extracting data at these points. I realize that there is a tool available for this on QGIS (Points Along Geometry); however, I am hoping to have these combined in one sleek tool. As of right now, your tool is the best for adding data to these points once they are created. A slower approach requires using multiple tools if you have different types of data (Add polygon attributes, Sample raster values, etc.)

Thanks! I look forward to hearing back from the community.

**Comment by borysiasty** [comment]
Hi, this plugin is no longer developed and I only keep it alive because there is still no alternative for sampling polygons. The correct way is using processing algorithms - you can combine them with the model builder, run in batch mode, call from Python scripts etc.
