### ISSUE TITLE
Feature request: Add support for QGSMeshLayer Type (QGIS > 3.6)

### ISSUE THREAD

**Issue by ZedeN1** [borysiasty/pointsamplingtool#16]
Would be great if point sampling tool worked with QGIS Mesh type layers. Similar to Profile Tool changes added in 4.1.6

**Comment by borysiasty** [comment]
Hi,
I don't plan any further work on this plugin. Now Processing algorithms are the way to go. There is already one, the Sample Raster Values and it would be quite easy to derive a new "Sample Mesh Value" from it.

**Comment by borysiasty** [comment]
See also #13
