### ISSUE TITLE
Errors when input vector layer is MultiPoint and output layer is shapefile

### ISSUE THREAD

**Issue by agiudiceandrea** [borysiasty/pointsamplingtool#17]
If the the layer containing sampling points is a MultiPoint vector layer and the output point vector layer is a shapefile layer, an empty shape file (with no features) is create and several errors are throwed:

WARNING    Feature creation error (OGR error: Attempt to write non-point (MULTIPOINT) geometry to point shapefile.)
WARNING    Feature creation error (OGR error: Attempt to write non-point (MULTIPOINT) geometry to point shapefile.)
WARNING    Feature creation error (OGR error: Attempt to write non-point (MULTIPOINT) geometry to point shapefile.)
WARNING    Feature creation error (OGR error: Attempt to write non-point (MULTIPOINT) geometry to point shapefile.)
WARNING    Feature creation error (OGR error: Attempt to write non-point (MULTIPOINT) geometry to point shapefile.)
WARNING    Feature creation error (OGR error: Attempt to write non-point (MULTIPOINT) geometry to point shapefile.)
WARNING    Feature creation error (OGR error: Attempt to write non-point (MULTIPOINT) geometry to point shapefile.)

**Comment by borysiasty** [comment]
@agiudiceandrea Big thanks!
