### ISSUE TITLE
question

### ISSUE THREAD

**Issue by marwen90** [borysiasty/pointsamplingtool#22]
Hi, great thanks for this invaluable plugin. However I have  a question, when I try to get data from my DSM model to point (in shp) which is located at the edge of two DSM pixels (or at the corner of 4 pixels), value of which pixel will be implemented to my point ?? it will be an interpolation of those two (four) values in vicinity? How can I change this - I am not a programist :( Can I for example get the highest value from pixels which contiguous (touch) my shp. point?? How can I do this ?? Thank you ina advance!

**Comment by borysiasty** [comment]
Hi,

No interpolation is performed, thus one of the pixels is sampled (I bet the lower-right). Unfortunately I don't know any existing tool that allows to adjust this behaviour.

BTW. this plugin is very old and unmaintained, please use the _Sample Raster Vales_ processing algorithm instead.

**Comment by marwen90** [comment]
Thanks for Your assistance! On the other hand, have you any idea how to
find the pixel with the highest value (DSM) in vicinity (searching distance
defined by DSM pixel resolution i.e. 2 meters)  of my point? Thanks for
your work! Greetings, Marcin!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Wolny
od wirusów. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

śr., 8 kwi 2020 o 19:23 Borys Jurgiel <notifications@github.com> napisał(a):
