### ISSUE TITLE
run pointsamplingtool in processing ?

### ISSUE THREAD

**Issue by Student-for-Life** [borysiasty/pointsamplingtool#23]
I tried to run point sampling tool as a script in the processing menu. It crashed and I am still trying to figure out how to get the processing plugin to load without crashing qgis - even though I removed the files from pointsamplingtool.  Any suggestions? Do you have a method to modify pointsamplingtool so that it will run under the processing menu? I tried some of the simple changes recommended in the qgis user manual to no avail. Thank you. Eme Furlong   emefurlong@gmail.com

**Comment by borysiasty** [comment]
PointSamplingTool and Processing algorithms have completely different architecture. If you want to write a processing algorithm, just do it from scratch. 

There is already the `Sample raster values` (`rastersampling`) processing algorithm, so I assume you need to sample polygons. Unfortunately the raster algoritm is C++ not Python, so it's not useful as an example.

The only code from PointSamplingTool that might be useful as an example is the main loop that actually iterates over sampling points and sampled polygons:
https://github.com/borysiasty/pointsamplingtool/blob/master/doPointSamplingTool.py#L374-L432

But I'm not sure if it's helpful at all, as it's unnecessarily complicated. All you need from this code is to iterate over points and polygons, and check if their geometries overlap. All the rest (GUI, selecting the layers and attributes to sample, writing to the output) is completely different in Processing, so PointSamlingTool is no example.

**Comment by Student-for-Life** [comment]
Thank you for your kind response. Just to mention I want to do point sampling from a combined database of 30 rasters. I don’t know why, but pointsamplingtool is the only code that works on this. When I use the raster sampling tool in processing, the tool will not recognize the combined raster geodatabase as input. Your tool was the only one that worked. What is your secret?

Anyway, thank you for your helpful advice.

Eme
