### ISSUE TITLE
Not working in QGIS 3.22

### ISSUE THREAD

**Issue by ppopoca** [borysiasty/pointsamplingtool#27]
Hi,

I've used the plugin several times in the past, but now, I doesn't seem to work. The window opens but it does not show any layer, not from points neither from layer to extract info from. I assume it's related to the newer version of QGIS.

I hope something can be done about it. Thanks!

**Comment by borysiasty** [comment]
Hi, I can't reproduce that issue. Please provide a sample dataset if it's still valid.

**Comment by ppopoca** [comment]
Hi, I don't have the problem anymore. Not sure what might have been the cause. Thanks anyway, great plugin you have developed.
