### ISSUE TITLE
Layers's order

### ISSUE THREAD

**Issue by alcio313** [borysiasty/pointsamplingtool#4]
How does it work the "Point sampling tool" order mechanism? how to change it in the first step without opening table manager?
https://goo.gl/photos/iTAd3QAAEBwqZTmAA

**Comment by borysiasty** [comment]
@alcio313 - I'm sorry for so late reply! I've overlooked this ticket. 

Do you mean the fields of the point layer? They should go as they are in the attribute table, no way to change the order to alphabetical or so.
