### ISSUE TITLE
Provide an error message if there is a CRS mismatch

### ISSUE THREAD

**Issue by jlmarino** [borysiasty/pointsamplingtool#5]
The Point Sampling Tool does not appear to work if the Coordinate Reference Systems of the layers do not match. However, the tool will run without error, appearing to have worked successfully. It may be helpful to either (a) prevent the Point Sampling Tool from executing if there is a CRS mismatch or (b) at least provide an error/warning prior to executing the Point Sampling Tool analysis if there is a CRS mismatch between any of the layers.

**Comment by borysiasty** [comment]
Fixed in 0.4.2
