### ISSUE TITLE
Unable to select layer

### ISSUE THREAD

**Issue by snow-raven** [borysiasty/pointsamplingtool#7]
I'm trying to resample a very large elevation grid, but am unable to load layers into the tool. The "Layer containing sampling points" menu does not populate or offer a drop-down list. 
I have tried uninstalling & reinstalling the plugin, updated my QGIS to the latest stable build, created a new project with just the DEM I want to resample, and tried resampling other DEMs, but the menu still does not populate. I haven't found any indication of this problem on any forums.

QGIS version
2.14.21-Essen
QGIS code revision
ea983fa869
Compiled against Qt
4.8.5
Running against Qt
4.8.5
Compiled against GDAL/OGR
2.2.3
Running against GDAL/OGR
2.2.3
Compiled against GEOS
3.5.0-CAPI-1.9.0
Running against GEOS
3.5.0-CAPI-1.9.0 r4084
PostgreSQL Client Version
9.2.4
SpatiaLite Version
4.3.0
QWT Version
5.2.3
PROJ.4 Version
493
QScintilla2 Version
2.7.2

**Comment by borysiasty** [comment]
@snow-raven I'm afraid you could misunderstood the plugin purpose. It has nothing to do with raster resampling. It just samples multiple rasters and polygons in given points - so first you need to load a point layer to the project. See the *About* tab in the plugin window.

For raster resampling algorithms, see the Processing Toolbox and the Raster menu.
