### ISSUE TITLE
Point sampling as a processing algorithm

### ISSUE THREAD

**Issue by barryrowlingson** [borysiasty/pointsamplingtool#9]
Could this code be used to create a processing toolbox algorithm to sample points on a raster? Then it could also be integrated into the graphical modeler.

**Comment by borysiasty** [comment]
I'll think about it when updating for QGIS 3 (what will unlikely happen before the release). 

Anyway I don't want to lose the interactive GUI in the "normal" mode and I didn't check yet how to use different ParametersPanels (one interactive, one static input-line based) for the two contexts. The Refactor Fields algorithm, for example, seems to not be modeller-friendly.

**Comment by borysiasty** [comment]
This feature has been implemented in core: https://github.com/qgis/QGIS/pull/7393
